package org.example.exception_exercise_2;public class Main {
}
